# Main clock
set_property PACKAGE_PIN AC18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]

create_clock -period 10.000 -name clk [get_ports "clk"]

# VGA
set_property -dict {PACKAGE_PIN T20  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {blue_out[0]}]
set_property -dict {PACKAGE_PIN R20  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {blue_out[1]}]
set_property -dict {PACKAGE_PIN T22  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {blue_out[2]}]
set_property -dict {PACKAGE_PIN T23  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {blue_out[3]}]

set_property -dict {PACKAGE_PIN R22  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {green_out[0]}]
set_property -dict {PACKAGE_PIN R23  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {green_out[1]}]
set_property -dict {PACKAGE_PIN T24  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {green_out[2]}]
set_property -dict {PACKAGE_PIN T25  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {green_out[3]}]

set_property -dict {PACKAGE_PIN N21  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {red_out[0]}]
set_property -dict {PACKAGE_PIN N22  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {red_out[1]}]
set_property -dict {PACKAGE_PIN R21  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {red_out[2]}]
set_property -dict {PACKAGE_PIN P21  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {red_out[3]}]

set_property -dict {PACKAGE_PIN M22  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {hor_sync}]
set_property -dict {PACKAGE_PIN M21  IOSTANDARD LVCMOS33  SLEW FAST} [get_ports {ver_sync}]

# Switches
set_property PACKAGE_PIN AA10 [get_ports {reset_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {reset_n}]

# sram
set_property PACKAGE_PIN D20 [get_ports {sram_addr[0]}]
set_property PACKAGE_PIN D18 [get_ports {sram_addr[1]}]
set_property PACKAGE_PIN E16 [get_ports {sram_addr[2]}]
set_property PACKAGE_PIN E18 [get_ports {sram_addr[3]}]
set_property PACKAGE_PIN E17 [get_ports {sram_addr[4]}]
set_property PACKAGE_PIN E20 [get_ports {sram_addr[5]}]
set_property PACKAGE_PIN F15 [get_ports {sram_addr[6]}]
set_property PACKAGE_PIN F18 [get_ports {sram_addr[7]}]
set_property PACKAGE_PIN H19 [get_ports {sram_addr[8]}]
set_property PACKAGE_PIN J16 [get_ports {sram_addr[9]}]
set_property PACKAGE_PIN J18 [get_ports {sram_addr[10]}]
set_property PACKAGE_PIN J20 [get_ports {sram_addr[11]}]
set_property PACKAGE_PIN G19 [get_ports {sram_addr[12]}]
set_property PACKAGE_PIN H17 [get_ports {sram_addr[13]}]
set_property PACKAGE_PIN F20 [get_ports {sram_addr[14]}]
set_property PACKAGE_PIN G17 [get_ports {sram_addr[15]}]
set_property PACKAGE_PIN F17 [get_ports {sram_addr[16]}]
set_property PACKAGE_PIN F19 [get_ports {sram_addr[17]}]
set_property PACKAGE_PIN H18 [get_ports {sram_addr[18]}]
set_property PACKAGE_PIN G20 [get_ports {sram_addr[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[19]}]
set_property PACKAGE_PIN E15 [get_ports {sram_ce[1]}]
set_property PACKAGE_PIN G15 [get_ports {sram_ce[2]}]
set_property PACKAGE_PIN K20 [get_ports {sram_ce[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_ce[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_ce[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_ce[3]}]
set_property PACKAGE_PIN M16 [get_ports {sram_dq[0]}]
set_property PACKAGE_PIN L19 [get_ports {sram_dq[1]}]
set_property PACKAGE_PIN L17 [get_ports {sram_dq[2]}]
set_property PACKAGE_PIN K18 [get_ports {sram_dq[3]}]
set_property PACKAGE_PIN L18 [get_ports {sram_dq[4]}]
set_property PACKAGE_PIN K17 [get_ports {sram_dq[5]}]
set_property PACKAGE_PIN K16 [get_ports {sram_dq[6]}]
set_property PACKAGE_PIN M17 [get_ports {sram_dq[7]}]
set_property PACKAGE_PIN H26 [get_ports {sram_dq[8]}]
set_property PACKAGE_PIN H23 [get_ports {sram_dq[9]}]
set_property PACKAGE_PIN H21 [get_ports {sram_dq[10]}]
set_property PACKAGE_PIN J26 [get_ports {sram_dq[11]}]
set_property PACKAGE_PIN L20 [get_ports {sram_dq[12]}]
set_property PACKAGE_PIN J19 [get_ports {sram_dq[13]}]
set_property PACKAGE_PIN J21 [get_ports {sram_dq[14]}]
set_property PACKAGE_PIN K21 [get_ports {sram_dq[15]}]
set_property PACKAGE_PIN B26 [get_ports {sram_dq[16]}]
set_property PACKAGE_PIN C22 [get_ports {sram_dq[17]}]
set_property PACKAGE_PIN A24 [get_ports {sram_dq[18]}]
set_property PACKAGE_PIN A23 [get_ports {sram_dq[19]}]
set_property PACKAGE_PIN E22 [get_ports {sram_dq[20]}]
set_property PACKAGE_PIN E23 [get_ports {sram_dq[21]}]
set_property PACKAGE_PIN C24 [get_ports {sram_dq[22]}]
set_property PACKAGE_PIN D23 [get_ports {sram_dq[23]}]
set_property PACKAGE_PIN B20 [get_ports {sram_dq[24]}]
set_property PACKAGE_PIN A20 [get_ports {sram_dq[25]}]
set_property PACKAGE_PIN C21 [get_ports {sram_dq[26]}]
set_property PACKAGE_PIN B21 [get_ports {sram_dq[27]}]
set_property PACKAGE_PIN A22 [get_ports {sram_dq[28]}]
set_property PACKAGE_PIN B22 [get_ports {sram_dq[29]}]
set_property PACKAGE_PIN D21 [get_ports {sram_dq[30]}]
set_property PACKAGE_PIN E21 [get_ports {sram_dq[31]}]
set_property PACKAGE_PIN H24 [get_ports {sram_dq[32]}]
set_property PACKAGE_PIN E26 [get_ports {sram_dq[33]}]
set_property PACKAGE_PIN G25 [get_ports {sram_dq[34]}]
set_property PACKAGE_PIN F24 [get_ports {sram_dq[35]}]
set_property PACKAGE_PIN F25 [get_ports {sram_dq[36]}]
set_property PACKAGE_PIN G24 [get_ports {sram_dq[37]}]
set_property PACKAGE_PIN G21 [get_ports {sram_dq[38]}]
set_property PACKAGE_PIN G26 [get_ports {sram_dq[39]}]
set_property PACKAGE_PIN F22 [get_ports {sram_dq[40]}]
set_property PACKAGE_PIN G22 [get_ports {sram_dq[41]}]
set_property PACKAGE_PIN C26 [get_ports {sram_dq[42]}]
set_property PACKAGE_PIN D24 [get_ports {sram_dq[43]}]
set_property PACKAGE_PIN E25 [get_ports {sram_dq[44]}]
set_property PACKAGE_PIN F23 [get_ports {sram_dq[45]}]
set_property PACKAGE_PIN D25 [get_ports {sram_dq[46]}]
set_property PACKAGE_PIN D26 [get_ports {sram_dq[47]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[34]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[36]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[37]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[38]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[39]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[40]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[41]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[42]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[43]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[44]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[45]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[46]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_dq[47]}]
set_property PACKAGE_PIN D19 [get_ports {sram_oen[1]}]
set_property PACKAGE_PIN U19 [get_ports {sram_oen[2]}]
set_property PACKAGE_PIN P16 [get_ports {sram_oen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_oen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_oen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_oen[3]}]
set_property PACKAGE_PIN J15 [get_ports {sram_wen[1]}]
set_property PACKAGE_PIN T19 [get_ports {sram_wen[2]}]
set_property PACKAGE_PIN P23 [get_ports {sram_wen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_wen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_wen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_wen[3]}]
set_property PACKAGE_PIN R26 [get_ports {sram_bhen[1]}]
set_property PACKAGE_PIN P20 [get_ports {sram_bhen[2]}]
set_property PACKAGE_PIN P18 [get_ports {sram_bhen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_bhen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_bhen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_bhen[3]}]
set_property PACKAGE_PIN K26 [get_ports {sram_blen[1]}]
set_property PACKAGE_PIN M20 [get_ports {sram_blen[2]}]
set_property PACKAGE_PIN R17 [get_ports {sram_blen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_blen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_blen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_blen[3]}]